batch_handler:
  SocketBatchHandler:
    address: 'localhost'
    port: 12345
book_keeper:
  LocalBookKeeper:
    file_name: '/Users/linogerlach/Projects/DUNE/WireCell/promptprocessing/data/bookkeeping/data_frame.csv'
file_handler:
  LocalFileHandler:
    input_dir: '/Users/linogerlach/Projects/DUNE/WireCell/promptprocessing/data/input'
    output_dir: '/Users/linogerlach/Projects/DUNE/WireCell/promptprocessing/data/output'
backlog_goal: 16
